version: 2.1

orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0
jobs:
  install-node:
    docker:
      - image: 'node:14-alpine'
    steps:
      #- checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - run: yarn build-prod
      - aws-s3/copy:
          from: dist/
          to: s3://poema.separovi.ch
          arguments: --recursive

workflows:
  build&deploy:
    jobs:
      - install-node
# workflows:
#   sample:
#     jobs:
#       - node:
#           version: '15.1'
#           steps:
#             - run: npm run build-prod
#           # after the node/test job completes, build the dist packages and save them to a workspace
#           post-steps:
#             - aws-s3/copy:
#                 from: dist/
#                 to: s3://poema.separovi.ch
#                 arguments: --recursive